lesson-36
TatianaBelova333/SKYPRO_ToDoList pull request #2
Opened 2022-10-27 17:59 UTC by TatianaBelova333

2022-10-27 20:12 UTC, painassasin requested changes

2022-10-27 20:12 UTC, painassasin commented on src/goals/models/dates.py
> +    def save(self, *args, **kwargs):
В Django для такого служат два параметра `auto_now_add` и `auto_now`. Нужно их прописать у полей `created` и `updated`, а этот метод удалить

2022-10-27 20:12 UTC, painassasin commented on src/goals/views/goal_category.py
> +        for goal in category.goals.all():
Тут ты делаешь один запрос SELECT чтобы получить все цели, а потом на каждую цель ты делаешь update (save) - много запросов

Тут можно обойтись одним update с фильтром

2022-10-27 20:12 UTC, painassasin commented on src/goals/serializers/goal_comment.py
> +        read_only_fields = ("id", "created", "updated", "user")
Тут нужно добавить поле `goal`, тогда не придется во принимать через `request` параметр `goal`

2022-10-27 21:21 UTC, TatianaBelova333 commented on src/goals/serializers/goal_comment.py
> +        read_only_fields = ("id", "created", "updated", "user")
Не совсем понимаю, как мне переписать тогда этот метод?
    def get_queryset(self):
        """Return queryset with goal categories filtered by current user and is_deleted status"""
        goal = self.request.query_params.get('goal')
        return GoalComment.objects.filter(user=self.request.user, goal=goal)

Мне же нужно фильтровать по goal тоже, иначе для каждой цели будут отображаться абсолютно все комментарии;

2022-10-28 10:36 UTC, TatianaBelova333 commented on src/goals/models/dates.py
> +    def save(self, *args, **kwargs):
исправила

2022-10-28 10:36 UTC, TatianaBelova333 commented on src/goals/views/goal_category.py
> +        for goal in category.goals.all():
исправила

2022-10-28 10:37 UTC, TatianaBelova333 commented on src/goals/serializers/goal_comment.py
> +        read_only_fields = ("id", "created", "updated", "user")
Здесь исправлять пока не буду, потому что если делать как в разборе домашки, то комментарии не фильтруются по целям.

2022-10-28 13:14 UTC, merged

2022-10-31 06:25 UTC, painassasin commented on src/goals/views/goal_category.py
> +        category.goals.all().update(status=Status.archived)
Тут можно без all
```python
category.goals.update(status=Status.archived)
```