Lesson 38
TatianaBelova333/SKYPRO_ToDoList pull request #4
Opened 2022-11-07 11:33 UTC by TatianaBelova333

2022-11-07 14:45 UTC, painassasin requested changes

2022-11-07 14:45 UTC, painassasin commented on deploy/docker-compose.yaml
> +      TELEGRAM_TOKEN: ${TELEGRAM_BOT_TOKEN}
Зачем эту переменную передавать через environment, мне кажется ее проще положить в .env

2022-11-07 14:45 UTC, painassasin commented on src/bot/admin.py
> +# Register your models here.
Забыла написать админку для бота)

2022-11-07 14:45 UTC, painassasin commented on src/bot/management/commands/runbot.py
> +                    if not tg_client.tg_user_exists(tg_user_id=tg_user_id) or not tg_client.tg_user_verified(tg_user_id=tg_user_id):
Очень много логики кладешь в метод, в идеале методы должны быть не более 25-30 строк, а у тебя уже много, при этом если добавится в бот еще функционал, код разрастется так, что им будет сложно управлять. Давай разобьем его хотя бы на несколько методов.

2022-11-07 14:45 UTC, painassasin commented on src/bot/serializers.py
> +        verification_code = data.get('verification_code')
Это же обязательное поле, там не должно быть `get`, принимай такие параметры через `[]`

2022-11-07 14:45 UTC, painassasin commented on src/bot/tests.py
> +# Create your tests here.
Файл не нужен, можно удалить

2022-11-07 14:45 UTC, painassasin commented on src/todolist/settings.py
> +TELEGRAM_BOT_TOKEN = env.str('TELEGRAM_BOT_TOKEN', default="5728255489:AAH21mfYsuvp3YANrzH1pkSkwt1xXrnONDc")
Дефолтно значение нужно убрать - это должно быть секретной информацией, а значит скрытой

2022-11-08 10:41 UTC, TatianaBelova333 commented on src/todolist/settings.py
> +TELEGRAM_BOT_TOKEN = env.str('TELEGRAM_BOT_TOKEN', default="5728255489:AAH21mfYsuvp3YANrzH1pkSkwt1xXrnONDc")
Это было временное решение, так как были локальные проблемы с .env. Забыла удалить

2022-11-08 10:42 UTC, TatianaBelova333 commented on deploy/docker-compose.yaml
> +      TELEGRAM_TOKEN: ${TELEGRAM_BOT_TOKEN}
В .env  эта переменная тоже есть)

2022-11-08 10:43 UTC, TatianaBelova333 commented on src/bot/tests.py
> +# Create your tests here.
done

2022-11-08 10:44 UTC, TatianaBelova333 commented on src/bot/serializers.py
> +        verification_code = data.get('verification_code')
done

2022-11-08 11:22 UTC, TatianaBelova333 commented on src/bot/admin.py
> +# Register your models here.
done

2022-11-09 13:57 UTC, TatianaBelova333 commented on src/bot/management/commands/runbot.py
> +                    if not tg_client.tg_user_exists(tg_user_id=tg_user_id) or not tg_client.tg_user_verified(tg_user_id=tg_user_id):
Поправила

2022-11-10 07:49 UTC, painassasin approved these changes

2022-11-10 07:50 UTC, painassasin approved these changes

2022-11-10 10:54 UTC, merged